# Generated by Django 5.1.2 on 2025-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, null=True)),
                ('option_a', models.CharField(max_length=100, null=True)),
                ('option_b', models.CharField(max_length=100, null=True)),
                ('option_c', models.CharField(max_length=100, null=True)),
                ('option_d', models.CharField(max_length=100, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
            ],
        ),
    ]
